---
output: html_notebook
title: "Pre Analysis top 7 edges."
---

<!-- The datasets to make this notebook are in SenseMyFEUP.Rmd
     The rest of the code is divided: 
          General information: April2016.Rmd 
          Timeseries functions: timeseries.R
          
    df_speed_top it is on preanalysis_course.Rmd
-->

# Map of top points 

```{r echo=FALSE}
#m_top7 <- m
m_top7
```

# Setting dataframe. 
 Filters: 
  *No parking edges.
  *Week days
  *Speed > 5
  *Hour between 8hr and 20h
```{r echo=FALSE}
# Setting the dataframe. No weekends and time between 8-20h.

df_superhotedges_april16pt <- df_speed_top

df_superhotedges_april16pt$time <- as.POSIXct(df_superhotedges_april16pt$seconds, origin="1970-01-01")

df_superhotedges_april16pt <- df_superhotedges_april16pt %>% 
  filter(hour(time) >=8, hour(time)<= 20, wday(time) != 1 , wday(time) != 7, (speed*18/5) > 5 ) 

df_superhotedges_april16pt$course <- factor(df_superhotedges_april16pt$course)

```
 
# 


# Hour discretization 

```{r echo=FALSE}
dfm_base %>% 
  filter(way_id == df_osm_edge_ids[,1] & course != 1.5 ) %>% 
  ggplot(aes(x= hour, fill = course)) + 
    geom_histogram(binwidth = 1) +
  facet_wrap(~day)+
  ggtitle("Sessions by hour and course (WW)")
```
 
```{r echo=FALSE}
day_hist1 <-  function(index) { dfm_base %>% 
  filter( day == index ) %>% 
  merge(y = df_osm_edge_ids, using = way_id) %>% 
  ggplot(aes(x= factor(hour))) +
  geom_histogram(aes(group=address, color=address), stat = "count") +
  facet_wrap(~course)  +
  ggtitle(paste("NºSessions by hour, edge and course in april:", index, sep = " " )) + 
  xlab("Hour") +
  ylab("Count") 
}

unique(dfm_base$day) %>% 
lapply(FUN = day_hist1)
```

```{r echo=FALSE}
df_superhotedges_april16pt <- df_superhotedges_april16pt %>% 
  mutate( period = case_when(hour(.$time) == 8 | 
                               hour(.$time) == 9 | 
                               hour(.$time) == 10 |
                               hour(.$time) == 11 |
                               hour(.$time) == 18 |
                               hour(.$time) == 19 |
                               hour(.$time) == 20  ~ factor(hour(.$time), levels = c(8,9,10,11,18,19,20,"midday","afternoon")), 
                             hour(.$time) == 12 |
                               hour(.$time) == 13 |
                               hour(.$time) == 14  ~ as.factor("midday"), 
                             hour(.$time) == 15 |
                               hour(.$time) == 16 |
                               hour(.$time) == 17 ~ as.factor("afternoon")))


```


# Congestion flow 

```{r echo=FALSE}
df_superhotedges_april16pt %>% 
  group_by(session_id) %>% 
  summarise(speed = mean(speed*18/5), n= n()) %>% 
  mutate(flow = case_when(.$speed <= 18 ~ "congestion", .$speed > 18 & .$speed < 30 ~ "sync", .$speed >= 30 ~"free" )) %>% 
  ggplot(aes(x=n, y = speed, color = flow)) + 
  geom_point() + 
  coord_cartesian(xlim = c(0,400)) + 
  xlab("Distinct sessions") + 
  ylab("Speed (km/h)") + 
  ggtitle("State discretization top 7 edges.")
```

```{r echo=FALSE}
df_superhotedges_april16pt %>% 
  group_by(session_id) %>% 
  summarise(speed = mean(speed*18/5)) %>% 
  mutate(flow = case_when(.$speed <= 18 ~ "congestion", .$speed > 18 & .$speed < 30 ~ "sync", .$speed >= 30 ~"free" )) %>% 
  ggplot(aes(x=speed, fill = flow)) + 
  geom_histogram(binwidth = 2) 
```



